# Generated by Django 2.2.5 on 2019-09-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20190908_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='f12a',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='f12b',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='f12c',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='f12d',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='f12e',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='f12f',
        ),
        migrations.AlterField(
            model_name='survey',
            name='f10',
            field=models.CharField(choices=[('1-To know about registration or voting process', '1-To know about registration or voting process'), ('2-To verify name on voter list', '2-To verify name on voter list'), ('3-To know my polling station', '3-To know my polling station'), ('4-To know details of my BLO', '4-To know details of my BLO'), ('5-To register a complaint', '5-To register a complaint'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, verbose_name='f10'),
        ),
    ]
