# Generated by Django 2.2.5 on 2019-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20190911_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='c5',
            field=models.CharField(blank=True, choices=[('0-Incorrect polling station', '0-Incorrect polling station'), ('1-Correct polling station', '1-Correct polling station')], max_length=128, null=True, verbose_name='c5'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d2',
            field=models.CharField(blank=True, choices=[('01-My vote matters', '01-My vote matters'), ('02-Voting is my right', '02-Voting is my right'), ('03-Voting is my duty', '03-Voting is my duty'), ('04-Because of enabling environment (free and fair) created by Election Commission', '04-Because of enabling environment (free and fair) created by Election Commission'), ('05-Because of accessible polling station', '05-Because of accessible polling station'), ('06-I got registered in electoral roll', '06-I got registered in electoral roll'), ('07-I got voter slip', '07-I got voter slip'), ('08-Candidate was good', '08-Candidate was good'), ('09-I voted for a political party', '09-I voted for a political party'), ('10-Cast vote due to threat or coercion', '10-Cast vote due to threat or coercion'), ('12-My family asked me to', '12-My family asked me to'), ('13-My friends asked me to', '13-My friends asked me to'), ('14-I had the option of NOTA', '14-I had the option of NOTA')], max_length=128, null=True, verbose_name='d2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3a',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3a'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3b',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3b'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3c',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3c'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3d',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3d'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3e',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3e'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3f',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3f'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3g',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3g'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3h',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3h'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3i',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3i'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3j',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3j'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d3k',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3k'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d4',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=8, null=True, verbose_name='d4'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e1',
            field=models.IntegerField(blank=True, default=99, null=True, verbose_name='e1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f9',
            field=models.CharField(blank=True, choices=[('0-None of the two', '0-None of the two'), ('1-Voter Helpline no 1950', '1-Voter Helpline no 1950'), ('2-Voter Helpline app only', '2-Voter Helpline app only'), ('3-Both of them', '3-Both of them')], max_length=128, null=True, verbose_name='f9'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g1',
            field=models.CharField(blank=True, choices=[('1-Illiterate', '1-Illiterate'), ('2-Primary school', '2-Primary school'), ('3-High School', '3-High School'), ('4-Higher secondary', '4-Higher secondary'), ('5-Diploma/ Certificate', '5-Diploma/ Certificate'), ('6-Graduate & above including professional/ Technical Courses', '6-Graduate & above including professional/ Technical Courses')], max_length=128, null=True, verbose_name='g1'),
        ),
    ]
