# Generated by Django 2.2.5 on 2019-09-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20190913_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetails',
            name='disabled',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes(in seeing)', '1-Yes(in seeing)'), ('2-Yes(in speech)', '2-Yes(in speech)'), ('3-Yes(in hearing)', '3-Yes(in hearing)'), ('4-Yes(in movement)', '4-Yes(in movement)')], max_length=128, null=True, verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='enrolled',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes(application in progress)', '1-Yes(application in progress)'), ('2-Yes(currently enrolled)', '2-Yes(currently enrolled)')], max_length=128, null=True, verbose_name='Enrolled'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='has_voted_in_assembly',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='Voted in Assembly election'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='has_voted_in_lok_sabha',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='Voted in Lok Sabha'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='migration',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='Migrated in last 1 year'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='relationship',
            field=models.CharField(blank=True, choices=[('01-Head', '01-Head'), ('02-Wife/Husband', '02-Wife/Husband'), ('03-Son/Daughter', '03-Son/Daughter'), ('04-Son in law/ daughter in law', '04-Son in law/ daughter in law'), ('05-Grandchild', '05-Grandchild'), ('06-Father/Mother', '06-Father/Mother'), ('07-Brother/Sister', '07-Brother/Sister'), ('08-Father-in-law/Mother-in-law', '08-Father-in-law/Mother-in-law'), ('09-Nephew/Niece', '09-Nephew/Niece'), ('10-Brother-in-law/Sister-in-law', '10-Brother-in-law/Sister-in-law'), ('11-Other relatives', '11-Other relatives'), ('12-Servant/Others', '12-Servant/Others')], max_length=128, null=True, verbose_name='Relationship with HH'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='sex',
            field=models.CharField(blank=True, choices=[('1-Male', '1-Male'), ('2-Female', '2-Female'), ('3-Third Gender', '3-Third Gender')], max_length=128, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a1',
            field=models.CharField(blank=True, choices=[('1-Received', '1-Received'), ('0-Not received', '0-Not received')], max_length=24, null=True, verbose_name='a1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a12',
            field=models.CharField(blank=True, choices=[('1-Completed', '1-Completed'), ('2-Entire HH absent for a long time', '2-Entire HH absent for a long time'), ('3-Postponed', '3-Postponed'), ('4-Refused (Pl. specify reasons)', 'Refused (Pl. specify reasons)'), ('5-HH/dwelling vacant', '5-HH/dwelling vacant'), ('6-Address of HH/dwelling not found', '6-Address of HH/dwelling not found')], max_length=64, null=True, verbose_name='a12'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a13',
            field=models.TextField(blank=True, null=True, verbose_name='a13'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a14',
            field=models.TextField(blank=True, null=True, verbose_name='a14'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a15',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=16, null=True, verbose_name='a15'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a16',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=16, null=True, verbose_name='a16'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a17',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=16, null=True, verbose_name='a17'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a2',
            field=models.TextField(blank=True, null=True, verbose_name='a2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a3',
            field=models.TextField(blank=True, choices=[('Chennai', 'Chennai'), ('Vellore', 'Vellore'), ('Salem', 'Salem'), ('Nagapattinam', 'Nagapattinam'), ('Thirunelveli', 'Thirunelveli'), ('Sivagangai', 'Sivagangai')], null=True, verbose_name='a3'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a3_code',
            field=models.IntegerField(blank=True, choices=[(603, 603), (605, 605), (608, 608), (618, 618), (622, 622), (628, 628)], null=True, verbose_name='a3_code'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a4',
            field=models.CharField(blank=True, choices=[('1-Urban', '1-Urban'), ('0-Rural', '0-Rural')], max_length=8, null=True, verbose_name='a4'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a6',
            field=models.TextField(blank=True, null=True, verbose_name='a6'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a7',
            field=models.TextField(blank=True, null=True, verbose_name='a7'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a8',
            field=models.TextField(blank=True, null=True, verbose_name='a8'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b1',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='b1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b12',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='b12'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b13',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='b13'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='b2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='b2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='c1',
            field=models.IntegerField(blank=True, default=98, null=True, verbose_name='c1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d1',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='d1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e2',
            field=models.CharField(blank=True, choices=[('0-18th Birthday', '0-18th Birthday'), ('1-1st January', '1-1st January'), ('99-Don’t Know', '99-Don’t Know')], max_length=128, null=True, verbose_name='e2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e3',
            field=models.CharField(blank=True, choices=[('0-Incorrect Date', '0-Incorrect Date'), ('1-Correct date', '1-Correct date'), ("99-Don't know", "99-Don't know")], max_length=128, null=True, verbose_name='e3'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e4a',
            field=models.CharField(blank=True, choices=[('1-Yes, saw it when I cast my vote', '1-Yes, saw it when I cast my vote'), ('2-Yes, have seen one in electoral literacy programme', '1-Yes, have seen one in electoral literacy programme'), ('3-Yes, have heard/read about it', '3-Yes, have heard/read about it'), ('4-No', '4-No')], max_length=128, null=True, verbose_name='e4a'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e4b',
            field=models.CharField(blank=True, choices=[('1-Yes, saw it when I cast my vote', '1-Yes, saw it when I cast my vote'), ('2-Yes, have seen one in electoral literacy programme', '1-Yes, have seen one in electoral literacy programme'), ('3-Yes, have heard/read about it', '3-Yes, have heard/read about it'), ('4-No', '4-No')], max_length=128, null=True, verbose_name='e4b'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e4c',
            field=models.CharField(blank=True, choices=[('1-Yes, saw it when I cast my vote', '1-Yes, saw it when I cast my vote'), ('2-Yes, have seen one in electoral literacy programme', '1-Yes, have seen one in electoral literacy programme'), ('3-Yes, have heard/read about it', '3-Yes, have heard/read about it'), ('4-No', '4-No')], max_length=128, null=True, verbose_name='e4c'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5a',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5a'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5b',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5b'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5c',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5c'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5d',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5d'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5e',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5e'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5f',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5f'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5g',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5g'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='e5h',
            field=models.CharField(blank=True, choices=[('1-Strongly disagree', '1-Strongly disagree'), ('2-Disagree', '2-Disagree'), ('3-Neither agree nor disagree', '3-Neither agree nor disagree'), ('4-Agree', '4-Agree'), ('5-Strongly agree', '5-Strongly agree')], max_length=128, null=True, verbose_name='e5h'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f1',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='f1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f10',
            field=models.CharField(blank=True, choices=[('1-To know about registration or voting process', '1-To know about registration or voting process'), ('2-To verify name on voter list', '2-To verify name on voter list'), ('3-To know my polling station', '3-To know my polling station'), ('4-To know details of my BLO', '4-To know details of my BLO'), ('5-To register a complaint', '5-To register a complaint'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, null=True, verbose_name='f10'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f11',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Somewhat', '1-Somewhat'), ('2-Yes', '2-Yes')], max_length=128, null=True, verbose_name='f11'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f2',
            field=models.CharField(blank=True, choices=[('1-Newspapers/magazines', '1-Newspapers/magazines'), ('2-TV advertisements and programmes', '2-TV advertisements and programmes'), ('3-Radio and FM channels', '3-Radio and FM channels'), ('4-Advertisements in cinemas', '4-Advertisements in cinemas'), ('5-Activity like Rallies, Prabhat Pheris, loudspeaker announcement', '5-Activity like Rallies, Prabhat Pheris, loudspeaker announcement'), ('6-Cultural/entertainments programmes', '6-Cultural/entertainments programmes'), ('7-Government offices circular', '7-Government offices circular'), ('8-Posters, hoardings and publicity materials', '8-Posters, hoardings and publicity materials'), ('9-NGO and Civil society Group', '9-NGO and Civil society Group'), ('10-Internet/ Social Media/Whatsapp', '10-Internet/ Social Media/Whatsapp'), ('11-SMS', '11-SMS'), ('12-Pledge letters/Sankalp patras through school students in the family', '12-Pledge letters/Sankalp patras through school students in the family'), ('13-At Polling Station', '13-At Polling Station'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, null=True, verbose_name='f2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f3',
            field=models.CharField(blank=True, choices=[('01-Date of voting and schedules', '01-Date of voting and schedules'), ('02-Voting is my right and duty', '02-Voting is my right and duty'), ('03-Cast vote as per choice and without taking any inducement', '03-Cast vote as per choice and without taking any inducement'), ('04-#GoRegister or Register', '04-#GoRegister or Register'), ('05-#GoVerify or Verify name in voter list', '05-#GoVerify or Verify name in voter list'), ('06-12 Identity documents allowed for Voting', '06-12 Identity documents allowed for Voting'), ('07-Facilities provided at polling station', '07-Facilities provided at polling station'), ('08-Priority voting for old and PwDs', '08-Priority voting for old and PwDs'), ('09-Voter helpline 1950 or Voter helpline app', '09-Voter helpline 1950 or Voter helpline app'), ('10-cVIGIL app related', '10-cVIGIL app related'), ('11-NVSP portal', '11-NVSP portal'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, null=True, verbose_name='f3'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f5',
            field=models.CharField(blank=True, choices=[('1-Ex-President APJ Abdul Kalam', '1-Ex-President APJ Abdul Kalam'), ('2-Cricketer M.S. Dhoni', '2-Cricketer M.S. Dhoni'), ('3-Sportsperson Mary Kom', '3-Sportsperson Mary Kom'), ('4-Sportsperson Saina Nehwal', '4-Sportsperson Saina Nehwal'), ('5-Actor Aamir Khan', '5-Actor Aamir Khan'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, null=True, verbose_name='f5'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f6',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='f6'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f7',
            field=models.CharField(blank=True, choices=[('1-To search name and other details on the Electoral Roll', '1-To search name and other details on the Electoral Roll'), ('2-To register/ make modifications online', '2-To register/ make modifications online'), ('3-To download registration forms', '3-To download registration forms'), ('4-To know polling details', '4-To know polling details'), ('5-To know election results', '5-To know election results'), ('6-To know details about the candidates/political parties', '6-To know details about the candidates/political parties'), ('7-To participate in online contests', '7-To participate in online contests'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, null=True, verbose_name='f7'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f8',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Somewhat', '1-Somewhat'), ('2-Yes', '2-Yes')], max_length=128, null=True, verbose_name='f8'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g2',
            field=models.CharField(blank=True, choices=[('1-Student', '1-Student'), ('2-Unemployed', '2-Unemployed'), ('3-unemployed available for work', '3-unemployed available for work'), ('4-Government Service', '4-Government Service'), ('5-Private Service', '5-Private Service'), ('6-Own enterprise', '6-Own enterprise'), ('7-Labourer/ Cultivator/ Agricultural and allied activities', '7-Labourer/ Cultivator/ Agricultural and allied activities'), ('8-Home maker', '8-Home maker'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, null=True, verbose_name='g2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g3',
            field=models.CharField(blank=True, choices=[('1-Never married', '1-Never married'), ('2-Married, no gauna', '2-Married, no gauna'), ('3-Married', '3-Married'), ('4-Widowed', '4-Widowed'), ('5-Separated/divorced', '5-Separated/divorced')], max_length=128, null=True, verbose_name='g3'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g4',
            field=models.CharField(blank=True, choices=[('1-SC', '1-SC'), ('2-ST', '2-ST'), ('3-OBC', '3-OBC'), ('4-Others', '4-Others')], max_length=128, null=True, verbose_name='g4'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g5a',
            field=models.CharField(blank=True, choices=[('1-Almost every day', '1-Almost every day'), ('2-At least once a weak', '2-At least once a weak'), ('3-Less than once a weak', '3-Less than once a weak'), ('4-Not for all', '4-Not for all')], max_length=128, null=True, verbose_name='g5a'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g5b',
            field=models.CharField(blank=True, choices=[('1-Almost every day', '1-Almost every day'), ('2-At least once a weak', '2-At least once a weak'), ('3-Less than once a weak', '3-Less than once a weak'), ('4-Not for all', '4-Not for all')], max_length=128, null=True, verbose_name='g5b'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g5c',
            field=models.CharField(blank=True, choices=[('1-Almost every day', '1-Almost every day'), ('2-At least once a weak', '2-At least once a weak'), ('3-Less than once a weak', '3-Less than once a weak'), ('4-Not for all', '4-Not for all')], max_length=128, null=True, verbose_name='g5c'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g5d',
            field=models.CharField(blank=True, choices=[('1-Almost every day', '1-Almost every day'), ('2-At least once a weak', '2-At least once a weak'), ('3-Less than once a weak', '3-Less than once a weak'), ('4-Not for all', '4-Not for all')], max_length=128, null=True, verbose_name='g5d'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='g6',
            field=models.CharField(blank=True, choices=[('1-Newspapers/magazines', '1-Newspapers/magazines'), ('2-Television', '2-Television'), ('3-Radio', '3-Radio'), ('4-Internet', '4-Internet'), ('5-Mobile Phone', '5-Mobile Phone'), ('6-Family/relatives/friends', '6-Family/relatives/friends'), ('99-Others (please specify)', '99-Others (please specify)')], max_length=128, null=True, verbose_name='g6'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='h1',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='h1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='h2',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='h2'),
        ),
    ]
