# Generated by Django 2.2.5 on 2019-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20190915_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='f5',
        ),
        migrations.AddField(
            model_name='survey',
            name='a6_name',
            field=models.TextField(blank=True, null=True, verbose_name='a6_name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='a6_part_no',
            field=models.TextField(blank=True, null=True, verbose_name='a6_part_no'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f5a',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='f5a'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f5b',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='f5b'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f5c',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='f5c'),
        ),
        migrations.AddField(
            model_name='survey',
            name='f5d',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes')], max_length=128, null=True, verbose_name='f5d'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='a5_code',
            field=models.TextField(blank=True, choices=[(23, 23), (12, 12), (15, 15), (18, 18), (43, 43), (50, 50), (38, 38), (46, 46), (83, 83), (84, 84), (85, 85), (87, 87), (160, 160), (161, 161), (163, 163), (164, 164), (219, 219), (222, 222), (223, 223), (226, 226), (184, 184), (185, 185), (186, 186), (187, 187)], null=True, verbose_name='a5_code'),
        ),
    ]
