# Generated by Django 2.2.5 on 2019-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20190915_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='d2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='d2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='d5',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='d5'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='f3',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='f3'),
        ),
    ]
