# Generated by Django 2.2.5 on 2019-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20190915_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='d3',
            field=models.CharField(blank=True, choices=[('0-No', '0-No'), ('1-Yes', '1-Yes'), ("9-Don't know", "9-Don't know")], max_length=128, null=True, verbose_name='d3'),
        ),
    ]
