# Generated by Django 2.2.5 on 2019-09-05 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(help_text='Auth token of the user.', max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('uuid', models.CharField(help_text='Unique identifier for a client device.', max_length=255, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auth token',
                'verbose_name_plural': 'Auth tokens',
                'db_table': 'auth_tokens',
                'unique_together': {('user', 'uuid')},
            },
        ),
    ]
